enum AppExceptionCode {
  noInternetConnection,
  noAccess,
  unknown,
  socket,
  serverNotAvailable,
  badRequest,
  loadFault,
  invalidEmail,
  disabledAccount,
  notRegistered,
  wrongPassword,
  usedEmail,
  notAllowedRegistrationMethod,
  weakPassword,
  wrongInputType,
  registrationError,
}
