name: core_ui
version: 0.0.1
publish_to: none
description: Project Core UI module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  domain:
    path: ../domain
  navigation:
    path: ../navigation


  flutter_svg: ^2.0.10+1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  grouped_list: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - ./resources/icons/
    - ./resources/images/

  fonts:
    - family: Pangram
      fonts:
        - asset: ./resources/fonts/pangram/Pangram-Bold.otf
          weight: 700
        - asset: ./resources/fonts/pangram/Pangram-Medium.otf
          weight: 500
        - asset: ./resources/fonts/pangram/Pangram-Regular.otf
          weight: 400
